[rhash] Fix error, revise dllexport/dllimport (#36950)
Pass `RHASH_XVERSION` as a number number, not as a string. General
error, but detected by Android NDK r26
~~~

vcpkg/buildtrees/rhash/src/v1.4.4-e609ae2b07.clean/librhash/rhash.c:877:10:
error: incompatible pointer to integer conversion returning 'char[1]'
from a function with result type 'rhash_uptr_t' (aka 'unsigned int')
[-Wint-conversion]
                return RHASH_XVERSION;
                       ^~~~~~~~~~~~~~
<command line>:2:24: note: expanded from macro 'RHASH_XVERSION'
#define RHASH_XVERSION ""
                       ^~
1 error generated.
~~~

Complement `dllexport` with `dllimport` for shared windows, and omit it
everywhere else.

Add missing pc file as if installed with official build system.