[cryptopp] Update the version to 8.1.0(Fix #3260) (#6010)
* allow building "ffmpeg.exe" 

add new feature "ffmpeg" which allows to build "ffmpeg.exe" - ex. : vcpkg install ffmpeg[x264,gpl,nonfree,ffplay,ffprobe,openssl,lzma,opencl,ffmpeg]:x64-windows-static --recurse

* allow building "ffmpeg.exe" 

add new feature "ffmpeg" which allows to build "ffmpeg.exe" - ex. : vcpkg install ffmpeg[x264,gpl,nonfree,ffplay,ffprobe,openssl,lzma,opencl,ffmpeg]:x64-windows --recurse

* fix static build of ffmpeg-executables

build ffplay.exe etc. failed because we tried to link ".a"-libraries

* allow building "ffmpeg.exe" 

add new feature "ffmpeg" which allows to build "ffmpeg.exe" - ex. : vcpkg install ffmpeg[x264,gpl,nonfree,ffplay,ffprobe,openssl,lzma,opencl,ffmpeg]:x64-windows-static --recurse

* allow building "ffmpeg.exe" 

add new feature "ffmpeg" which allows to build "ffmpeg.exe" - ex. : vcpkg install ffmpeg[x264,gpl,nonfree,ffplay,ffprobe,openssl,lzma,opencl,ffmpeg]:x64-windows --recurse

* fix static build of ffmpeg-executables

build ffplay.exe etc. failed because we tried to link ".a"-libraries

* Remove duplicate feature entries

* [clapack] Fix linux build

* [openblas] Remove restriction of build static lib on Linux

* Update ports/openblas/portfile.cmake

Co-Authored-By: kafeg <v31337@gmail.com>

* [ffmpeg] bump control version number

* [ffmpeg] switch to vcpkg_extract_source_archive_ex

* add parallel-hashmap package

* update version of package

* Check scripts/cmake/* and buildsystems/vcpkg.cmake for changes when hashing

* [cryptopp] Update the version to 8.1.0(Fix #3260)

* [darknet] add compatibility with OpenCV 4 (#6018)

* [curl] Bump CONTROL version (#6012)

* [sdl1]Fix sdl1 conflict with sdl2 (#6011)

* Use Opus CMake #4875 (#6007)

* Print what port installed confliciting files

* Revert "Print what port installed confliciting files"

This reverts commit 79682317c9e087dc1d1ae450e3edd03b0fa0cc59.

* Complete revert of accidental merge b1b7ec5c0be3a3b0

* [activemq-cpp] Add activemq-cpp library (#6017)

* [fix][ffmpeg] changing $PATH separator for Linux (#6015)

* [fix][ffmpeg] changing $PATH separator for Linux

Using a semicolon in $PATH might break on some flavors of Linux, eg Docker based on Ubuntu 18.04.

* Enable openssl:arm64-windows

* Add missing dependency for static Qt builds

* Enable pcre:arm64-windows

Update sljitConfigInternal.h for ARM64, resolve error C2375: 'FlushInstructionCache': redefinition; different linkage

* Enable pcre:arm64-windows

Update format

* Enable pcre2:arm64-windows

Update sljitConfigInternal.h for ARM64

* partial update for testing

* add git hash

* Revert "add git hash"

This reverts commit 1a3b388a911f844e6907cc9058728e2a3bdda419.

* Revert "partial update for testing"

This reverts commit 880181892e83b89657207777b1f2ce40fe3d31cb.

* [openssl-windows] Bump version number

* [pcre2] Bump version number

* [openvdb] Fix openvdb[tools] build failures (#6028)

* Update CONTROL

Bump the version in CONTROL file

* Update CONTROL

Bump the version in CONTROL file

* Update CONTROL

Revert version number since @grdowns already bumps version number

* Add --no-recurse switch to depend-info command.

* Add -allowAppleClang option to bootstrap.sh. (fixes #4698) (#5915)

* Add -allowAppleClang option to bootstrap.sh. (fixes #4698)

* [vcpkg-bootstrap] Simplify appleclang changes and reformat

* [vcpkg-bootstrap] Remove enviroment variable VCPKG_ALLOW_APPLE_CLANG

* [distorm, scylla_wrapper, devicenameresolver] init (#4170)

* distorm init

* scylla wrapper init

* devicenameresolver init

* [devicenameresolver][distorm][scylla-wrapper] Cleanup and mark libraries as dll-only.

* Bumb version number for qt5-base port

* [devil/libcopp/spaceland] stable cmake config (#6046)

* [darknet] sync with community expected version, add fixes for downstream projects (#6047)

* Print what port installed confliciting files (#6037)

* [PEGTL] Upgrade to 2.8.0

Migration guide:
https://github.com/taocpp/PEGTL/blob/master/doc/Migration-Guide.md#version-280

* [docs] Add VCPKG_CMAKE_SYSTEM_VERSION (#6061)

* Add help entry for depend-info

* [jsoncons] add port

* Bump version numbers, fix system name check

* [libpqxx]Update to version 6.4.3

* Add missing compiler flags