[libsodium] update to 1.0.19 (#35753)
* [libsodium] update to 1.0.19

* Fix config error

* Fixes cnats and proxygen failed with undefined reference to `_crypto_aead_aegis128l_pick_best_implementation' and `_crypto_aead_aegis256_pick_best_implementation'

* Fixes undefined reference to `aegis128l_aesni_implementation' and `aegis256_aesni_implementation'