[EAThread][EASTL] Added EAThread and modified EASTL (#8861)
* [EAThread][EASTL] Added EAThread and modified EASTL

EABase has now also been seperated from EASTL.
EASTL now copies CommonCppFlags.cmake as it is used by EAThread.

* Fix EABase

* Fix EABASE include for EASTL

* Improve EASTL

Still need to fix
The /debug/lib/cmake folder should be merged with /lib/cmake into /share/eastl
Found 3 error(s). Please correct the portfile:
    E:\vcpkg\ports\eastl\portfile.cmake
-- Performing post-build validation done
Error: Building package eastl:x64-windows-static failed with: POST_BUILD_CHECKS_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: eastl:x64-windows-static
  Vcpkg version: 2019.09.12-nohash

* Base pass one Thread

* Fix config errors and add `vcpkg_fixup_cmake_targets`

* Add required changes for fails

* x86-windows should also fail

* Revert adding `vcpkg_fail_port_install(ON_TARGET "Windows" ...)`

* Remove `eastl:arm64-windows=fail` from ci.baseline.txt

* Merge CONTROL descriptions into one line