[libodb] Fix compilation errors under Linux (#38352)
Fix one of [32398](https://github.com/microsoft/vcpkg/issues/32398)
issue.
```
/mnt/vcpkg/buildtrees/libodb/src/libodb-2-59eaf93c2b.clean/odb/details/shared-ptr/base.hxx:38:49: error: ISO C++17 does not allow dynamic exception specifications
   38 | operator new (std::size_t, odb::details::share) throw (std::bad_alloc);
      |                                                 ^~~~~
/mnt/vcpkg/buildtrees/libodb/src/libodb-2-59eaf93c2b.clean/odb/details/shared-ptr/base.hxx:65:34: error: ISO C++17 does not allow dynamic exception specifications
   65 |       operator new (std::size_t) throw (std::bad_alloc);
      |                                  ^~~~~
/mnt/vcpkg/buildtrees/libodb/src/libodb-2-59eaf93c2b.clean/odb/details/shared-ptr/base.hxx:68:41: error: ISO C++17 does not allow dynamic exception specifications
   68 |       operator new (std::size_t, share) throw (std::bad_alloc);
      |                                         ^~~~~
In file included from /mnt/vcpkg/buildtrees/libodb/src/libodb-2-59eaf93c2b.clean/odb/details/shared-ptr/base.hxx:108,
                 from /mnt/vcpkg/buildtrees/libodb/src/libodb-2-59eaf93c2b.clean/odb/details/shared-ptr/base.cxx:5:
/mnt/vcpkg/buildtrees/libodb/src/libodb-2-59eaf93c2b.clean/odb/details/shared-ptr/base.ixx:67:34: error: ISO C++17 does not allow dynamic exception specifications
   67 |     operator new (std::size_t n) throw (std::bad_alloc)
      |                                  ^~~~~
/mnt/vcpkg/buildtrees/libodb/src/libodb-2-59eaf93c2b.clean/odb/details/shared-ptr/base.ixx:73:41: error: ISO C++17 does not allow dynamic exception specifications
   73 |     operator new (std::size_t n, share) throw (std::bad_alloc)
      |                                         ^~~~~
/mnt/vcpkg/buildtrees/libodb/src/libodb-2-59eaf93c2b.clean/odb/details/shared-ptr/base.cxx:57:48: error: ISO C++17 does not allow dynamic exception specifications
   57 | operator new (size_t n, odb::details::share s) throw (std::bad_alloc)
```
Fix the syntax not supported by C++17 and modify the export file name.
- [X] Changes comply with the [maintainer
guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [ ] ~~SHA512s are updated for each updated download.~~
- [ ] ~~The "supports" clause reflects platforms that may be fixed by
this new version.~~
- [X] Any fixed [CI
baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)
entries are removed from that file.
- [ ] ~~Any patches that are no longer applied are deleted from the
port's directory.~~
- [X] The version database is fixed by rerunning `./vcpkg x-add-version
--all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

Usage test pass with following triplets:

```
x64-windows
```
Compile test pass with following triplets:
```
x64-windows
x64-linux
```