[lua] Fix compiler error of lua[tools] (#29897)
* Fix linux tools can't compile with undefined reference to `sin'

* update port version

* update baseline.json

* fix duplicate FIND_LIBRARY (LIB_MATH NAMES m) & fix linking of luac is missing math libs

* update lua port version in version database

---------

Co-authored-by: tobias.funk <tobias.funk@nortonlifelock.com>